name: reviewercalls
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pyyaml>=6.0.3
  - requests>=2.32.5
  - aiohttp>=3.13.3
  - validators>=0.35.0
  - pytest>=9.0.2
  - pytest-asyncio>=1.3.0
  - pip
  - pip:
    - ddgs>=9.10.0
